[profile.default]
solc-version = "0.8.24"
libs = ['lib']
optimizer = true
optimizer_runs = 420_000
fuzz_max_global_rejects = 420_000

gas_reports = [
    "Ghosts",
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts",
    "@pandora/=lib/erc404/contracts",
    "@pandoraLegacy/=lib/erc404-legacy/src"
]

[rpc_endpoints]
blast = "${RPC_URL}"
blastSepolia = "${TESTNET_RPC_URL}"

[etherscan]
blastSepolia = { key = "${ETHERSCAN_API_KEY}" }
blast = { key = "${ETHERSCAN_API_KEY}" }
